name: Code Style
on: [push]

jobs:
  check_code_style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest
    - name: Run `black` for code formatting
      run: black --check .
    - name: Run `pytype` for checking types
      uses: theahura/pytypes-action@main
      with:
        args: -d import-error
